name: CI + CD

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Name of the environment which will be handled'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - acc
          - prod

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Compile
        run: echo Hello, world!
    
  DeployDev:
    name: Deploy to Dev 
    if: ${{ ( github.event.ref != 'refs/heads/main' ) || ( ( github.event_name  == 'workflow_dispatch' ) && ( github.event.inputs.environment  == 'dev' ))}}
    needs: [Build]
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy
        run: |
          echo "I am deploying to dev!"
          echo "I am deploying to ${{ github.event.client_payload.environment }}"
          find | grep -v './.git'
    
  DeployTest:
    name: Deploy to Test 
    if: ${{ ( github.event.ref == 'refs/heads/main' ) || ( ( github.event_name  == 'workflow_dispatch' ) && ( github.event.inputs.environment  == 'test' ) ) }}
    needs: [Build]
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Deploy
        run: |
          echo "I am deploying to test"
          echo "I am deploying to ${{ github.event.client_payload.environment }}"
          find | grep -v './.git'

  DeployAcc:
    name: Deploy to Acc 
    if: ${{ ( github.event.ref == 'refs/heads/main' ) || ( ( github.event_name  == 'workflow_dispatch' ) && ( github.event.inputs.environment  == 'acc' ) ) }}
    needs: [DeployTest]
    runs-on: ubuntu-latest
    environment: acc
    steps:
      - name: Deploy
        run: |
          echo "I am deploying to acc"
          echo "I am deploying to ${{ github.event.client_payload.environment }}"
          find | grep -v './.git'
            
  DeployProd:
    name: Deploy to Prod
    if: ${{ ( github.event.ref == 'refs/heads/main' ) || ( ( github.event_name  == 'workflow_dispatch' ) && ( github.event.inputs.environment  == 'prod' ) ) }}
    needs: [DeployAcc]
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy
        run: |
          echo "I am deploying to prod"
          echo "I am deploying to ${{ github.event.client_payload.environment }}"
          find | grep -v './.git'
    
