name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
    
  DeployDev:
    name: Deploy to Dev 
    if: github.event.ref != 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
      - name: Deploy
        run: echo "I am deploying to ${{ env.environment }}!"
    
  DeployTest:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployDev]
    runs-on: ubuntu-latest
    environment: 
      name: acc
    steps:
      - name: Deploy
        run: echo "I am deploying to ${{ env.environment }}!"

  DeployAcc:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployTest]
    runs-on: ubuntu-latest
    environment: 
      name: acc
    steps:
      - name: Deploy
        run: echo "I am deploying to ${{ env.environment }}!"
            
  DeployProd:
    name: Deploy to Production 
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployAcc]
    runs-on: ubuntu-latest
    environment: 
      name: prod
    steps:
      - name: Deploy
        run: echo "I am deploying to ${{ env.environment }}!"
    
