name: CI + CD

on:
  push:
  workflow_dispatch:

jobs:
  # Build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  # 
  #     - name: Compile
  #       run: echo Hello, world!
    
  DeployDev:
    name: Deploy to Dev 
    if: github.event.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy
        run: echo "I am deploying to ${{ environment }}!"
    
  DeployTest:
    name: Deploy to Test 
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Deploy
        run: echo "I am deploying to ${{ environment }}!"

  DeployAcc:
    name: Deploy to Acc 
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployTest]
    runs-on: ubuntu-latest
    environment: acc
    steps:
      - name: Deploy
        run: echo "I am deploying to ${{ environment }}!"
            
  DeployProd:
    name: Deploy to Prod
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployAcc]
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy
        run: echo "I am deploying to ${{ environment }}!"
    
